### ISSUE TITLE
增加字典文件之后出现"段错误"

### ISSUE THREAD

**Issue by RJustice** [imaben/php-akm#10]
php版本: 7.4

编辑整个扩展和加载都没问题, 但是当在字典文件夹中增加字典文件后, 运行会出现段错误, 然后nginx访问提示找不到对应的字典

**Comment by RJustice** [comment]
```
#0  0x000055f849c2f10b in zend_hash_rehash ()
#1  0x000055f849c307f0 in zend_hash_index_add_new ()
#2  0x000055f849c35ee6 in zend_list_insert ()
#3  0x000055f849c35fb9 in zend_register_resource ()
#4  0x000055f849bd7b27 in _php_stream_alloc ()
#5  0x000055f849bded9b in _php_stream_fopen_from_fd ()
#6  0x000055f849bdf1fd in _php_stream_fopen ()
#7  0x000055f849bda9fa in _php_stream_open_wrapper_ex ()
#8  0x00007f409963e03b in akm_build_tree (filename=filename@entry=0x55f84b2396d3 "dd", fullpath=fullpath@entry=0x7ffc63a5e8c0 "/data/dict/dd") at /usr/local/src/php-akm/akm.c:99
#9  0x00007f409963e28a in akm_scan_directory (dirname=dirname@entry=0x55f84b2395d0 "/data/dict/", callback=0x7f409963df60 <akm_build_tree>) at /usr/local/src/php-akm/akm.c:162
#10 0x00007f409963e31c in akm_dict_ht_init () at /usr/local/src/php-akm/akm.c:183
#11 zm_startup_akm (type=<optimized out>, module_number=<optimized out>) at /usr/local/src/php-akm/akm.c:524
#12 0x000055f849c25e0c in zend_startup_module_ex ()
#13 0x000055f849c25e9c in zend_startup_module_zval ()
#14 0x000055f849c32f82 in zend_hash_apply ()
#15 0x000055f849c2618a in zend_startup_modules ()
#16 0x000055f849bc0c93 in php_module_startup ()
#17 0x000055f849ca9f8d in php_cli_startup ()
#18 0x000055f849a2a124 in main ()
```


我使用了master和v0.0.1分支都有如此错误

**Comment by imaben** [comment]
7.4还没适配过，今天看一下！

**Comment by imaben** [comment]
@RJustice fixed

**Comment by RJustice** [comment]
感谢.

**Comment by imaben** [comment]
@RJustice 使用最新的v0.0.2
